<?php
/** @var Yarmolich\CustomerStatus\Block\Form\Status $block */
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl(
    $block->getUrl('customer/account/saveStatus')
) ?>" method="post" id="form-validate" enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      autocomplete="off">
    <fieldset class="fieldset info" style="float: inherit;">
        <?= $block->getBlockHtml('formkey') ?>
        <div class="field">
            <label class="label"
                   for="customer_status"><span>Status</span></label>
            <div class="control">
                <input type="text" id="customer_status"
                       name="customer_status"
                       value="<?= $block->getAttribute('customer_status') ?>"
                       class="input-text">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary"
                    title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
                <span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>